baseURL = "https://dservgun.github.io/"
languageCode = "en-us"
title = "Enhanced Aerobic Bio-remediation of Chlorinated Solvents using VaporRemed - Field Report. Sarva Bio Remed, LLC."
copyright = "Dinkar Ganti, 2020, All Rights Reserved."
theme = "ananke"
